version: "3.8"

services:
  # API Principal
  company-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=company_db
      - MONGO_COLLECTION=companies
      - RABBITMQ_URI=amqp://rabbitmq:5672/
      - QUEUE_NAME=company_events
      - LOG_LEVEL=info
    depends_on:
      - mongodb
      - rabbitmq
    restart: unless-stopped

  # MongoDB
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=company_db
    restart: unless-stopped

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  mongodb_data:
  rabbitmq_data:
